stages:
  - build
  - ci
  - release
default:
  before_script:
    - env | sort
  interruptible: true
  image: registry.agibot.com/ai-platform/agibot-forge/dev:25.04-latest
  retry:
    max: 2
    when: runner_system_failure
include:
  - local: .gitlab/workflows/**.yml
